IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'UQ_MyTable_MyConstraint')
BEGIN
    ALTER TABLE [dbo].[MyTable] DROP CONSTRAINT [UQ_MyTable_MyConstraint];
END

ALTER TABLE [dbo].[MyTable]
ADD CONSTRAINT [UQ_MyTable_MyConstraint] UNIQUE ([Col1],[Col2]);
